apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainforge
  template:
    metadata:
      labels:
        app: chainforge
    spec:
      containers:
      - name: chainforge
        image: chainforge:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chainforge
spec:
  selector:
    app: chainforge
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 